safe:           false
auto:           false
server:         false
server_port:    4000
base-url:       /
source:         .
destination:    _site
plugins:        ./_plugins

future:         true
lsi:            false
pygments:       false
markdown:       rdiscount
permalink:      pretty

domain:         http://danielcbaldwin-blog.heroku.com
paginate:       5

disqus:
    id:         danielbaldwinblog

exclude:        ["colors.txt", "CNAME", "config.ru", ".gems", "contact-me.html_old", "Gemfile", "Gemfile.lock"]