safe:           false
auto:           false
server:         false
server_port:    4000
base-url:       /
source:         .
destination:    ./_site
plugins:        ./_plugins

future:         true
lsi:            false
pygments:       false
markdown:       rdiscount
permalink:      pretty

domain:         http://localhost:4000
paginate:       5

disqus:
    id:         danielbaldwinblog

exclude:        ["colors.txt", "CNAME", "404.html", "config.ru", ".gems", "contact-me.html_old"]